### ISSUE TITLE
SugarML breaks support for nesting (extends, include)

### ISSUE THREAD

**Issue by mrmlnc** [static-dev/html-whitespace-parser#9] opened 2016-11-11 10:49 UTC
Hello,

I created a minimal example to reproduce this problem: https://github.com/mrmlnc/posthtml-bug

The result of the work is not HTML and includes not expanded `include` tag 💣:

```html
doctype html

html(lang="ru")
	head
		p world
		include(src="templates/head.sml")  // <---------------------- 🎈🎈🎈 
		p My first SML page
```

But if I remove `SugarML` syntax (sml -> html) from my repository then I get correct result:

```html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <p>world</p>
    <title>Hello, world</title>
    <p>My first SML page</p>
  </head>
</html>
```

P.S.: works fine in Reshape... 😢

**Comment by michael-ciniawsky** [comment] 2016-11-11 11:33
Confirmed  `posthtml-include` doesn't have access to the parser, it just loads the include.src atm. 

Right now I work on `posthtml-include` anyways so good catch :+1:, could you try with [posthtml-modules](https://github.com/posthtml/posthtml-modules/issues) it runs a posthtml instance on the includes, this should maybe become part of the include plugin :)

**Comment by michael-ciniawsky** [comment] 2016-11-11 11:34
Reshape accesses the parser, thats why it works flamlessly

**Comment by michael-ciniawsky** [comment] 2016-11-13 07:02
@mrmlnc I close the issue here, since it's related to `posthtml-include` :)

**Closed as completed by michael-ciniawsky** 2016-11-13 07:02 UTC
